
# Tasks to Install Prometheus Monitoring Tool

- name: Install Prometheus
  apt:
    name: prometheus
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: Enabling Prometheus Performance Tool
  service:
    name: prometheus
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"

- name: Restarting Apache Service for Ubuntu
  service:
    name: prometheus
    state: restarted
    enabled: true
  when: ansible_distribution == "Ubuntu"
